wandb_version: 1

batch_size:
  desc: null
  value: 32
dropout1:
  desc: null
  value: 0.14422237216667763
dropout2:
  desc: null
  value: 0.20800596660942364
dropout3:
  desc: null
  value: 0.06323272370470817
epochs:
  desc: null
  value: 50
kernel1:
  desc: null
  value: 11
kernel2:
  desc: null
  value: 11
kernel3:
  desc: null
  value: 7
kmesh_points:
  desc: null
  value: 150
l_nn:
  desc: null
  value: 250
learning_rate:
  desc: null
  value: 3
output1:
  desc: null
  value: 64
output2:
  desc: null
  value: 32
output3:
  desc: null
  value: 16
training_noise_level:
  desc: null
  value: 0.05
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700118037.241725
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.15.9
      8:
      - 1
      - 3
      - 5
