data_dir='dataset_partial/'
random_seed=11992
spectra_data_path='output_ave_test_kx.csv'
gr_data_path=['gr.csv','gr_U.csv','gr_F.csv']
kmesh_path='kmesh.txt'
rmesh_path='rmesh.txt'
kmesh_bound=[1.5,8.5]
rmesh_bound=[1.5,5.5]
k_win_range=[2.0,8.0]
dx=2
window_func= 'hanning'
kweight=3
batch_size=64
lr=1e-2
training_noise_level=0.1
kmesh_points=200
rmesh_points=150
concate=true
partial_gr=true

[concate_details]
gr_F_range=[1.5,3.5]
gr_U_range=[3.0,5.5]
rpoints_ratio=[0.6,0.4]
